language: rust

sudo: false
cache:
  - apt
  - cargo

include_base: &BASE
  addons:
    apt:
      sources: &BASE_SOURCES
        - ubuntu-toolchain-r-test
      packages: &BASE_PACKAGES
        - libelf-dev
        - lib32z1-dev
        - libedit-dev
        - libdw-dev
        - binutils-dev
        - libiberty-dev
  before_install:
    - export LLVM_VERSION_DASH=${LLVM_VERSION/./-}
    - export LLVM_VERSION_SHORT=${LLVM_VERSION/./}
    - export PATH=/usr/lib/llvm-${LLVM_VERSION}/bin/:$HOME/.local/bin:$PATH
    - export LLVM_PATH=/usr/share/llvm-${LLVM_VERSION}/cmake/
    - sed -i -e 's/llvm-sys = ".*"/llvm-sys = "'${LLVM_VERSION_SHORT}'"/' Cargo.toml
  script:
    - cargo build --no-default-features --features "llvm${LLVM_VERSION_DASH}" --release
    - cargo test --no-default-features --features "llvm${LLVM_VERSION_DASH}" --verbose --release

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - env:
        - LLVM_VERSION="3.6"
      <<: *BASE
      addons:
        apt:
          sources:
            - *BASE_SOURCES
            - llvm-toolchain-precise-3.6
          packages:
            - *BASE_PACKAGES
            - llvm-3.6-dev

    - env:
        - LLVM_VERSION="3.7"
      <<: *BASE
      addons:
        apt:
          sources:
            - *BASE_SOURCES
            - llvm-toolchain-precise-3.7
          packages:
            - *BASE_PACKAGES
            - llvm-3.7-dev
    - env:
        - LLVM_VERSION="3.8"
      <<: *BASE
      addons:
        apt:
          sources:
            - *BASE_SOURCES
            - llvm-toolchain-precise-3.8
          packages:
            - *BASE_PACKAGES
            - llvm-3.8-dev
    - deploy: # Documentation build; Only latest supported LLVM version for now
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
        keep-history: false
        local-dir: target/doc/
        on:
          branch: master
      script:
        - cargo doc --no-default-features --features llvm3-8
        - echo '<meta http-equiv="refresh" content="1; url=inkwell/index.html">' > target/doc/index.html
      after_success:
      rust: nightly
      addons:
        apt:
          sources:
            - *BASE_SOURCES
            # - llvm-toolchain-precise-3.6
            # - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.8
          packages:
            - *BASE_PACKAGES
            # - llvm-3.6-dev
            # - llvm-3.7-dev
            - llvm-3.8-dev

env:
  global:
    - RUSTFLAGS="-C link-dead-code -C target-cpu=native"

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov-build &&
  cd ../.. &&
  rm -rf kcov-master &&
  for file in $(find . -regextype posix-extended -regex "./target/debug/test(\w|-)+"); do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib,tests --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"

notifications:
  email: false
