name: Test Suite

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: "LLVM ${{ matrix.llvm-version[0] }}: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        llvm-version:
          - ["3.6", "3-6"]
          - ["3.7", "3-7"]
          - ["3.8", "3-8"]
          # - ["3.9", "3-9"]
          - ["4.0", "4-0"]
          - ["5.0", "5-0"]
          - ["6.0", "6-0"]
          - ["7.0", "7-0"]
          - ["8.0", "8-0"]
          - ["9.0", "9-0"]
          - ["10.0", "10-0"]
          - ["11.0", "11-0"]
          - ["12.0", "12-0"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.4.1
        with:
          version: ${{ matrix.llvm-version[0] }}
      - name: Build
        run: cargo build --release --features llvm${{ matrix.llvm-version[1] }} --verbose
      - name: Run tests
        run: cargo test --release --features llvm${{ matrix.llvm-version[1] }} --verbose
